# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NoteApp
   pod 'RealmSwift', '~> 3.7'
   pod 'ReactiveSwift', '~> 3.0'
   pod 'ReactiveCocoa', '~> 7.0'
   
end
